GuestBookCore/Models/Entities/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace GuestBookCore.Models.Entities
{
    public class Comment
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public DateTime Date { get; set; }
        public string Text { get; set; }
    }
}

GuestBookCore/Models/ViewModels/CommentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace GuestBookCore.Models.ViewModels
{
    public class CommentViewModel
    {
        [Required(ErrorMessage ="Не введено имя пользователя!")]
        [MinLength(3,ErrorMessage ="Длина имени пользователя должна быть не короче 3 символов!")]
        [Display(Name ="Имя пользователя")]
        public string Username { get; set; }
        [Display(Name ="Комментарий")]
        public string Text { get; set; }
    }
}

GuestBookCore/Models/ViewModels/ErrorViewModel.cs
using System;

namespace GuestBookCore.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GuestBookCore/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using GuestBookCore.Data;
using GuestBookCore.Models.Entities;
using GuestBookCore.Models.ViewModels;

namespace GuestBookCore.Controllers
{
    public class CommentController : Controller
    {

        private readonly CommentDbContext _dbContext;

        public CommentController(CommentDbContext dbContext)
        {
            _dbContext = dbContext;
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]        
        public IActionResult Create(CommentViewModel model)
        {
            if(ModelState.IsValid)
            {
                _dbContext.Add(new Comment { Username = model.Username, Date = DateTime.Now, Text = model.Text });
                _dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Ошибка ввода!");
            }
            return View(model);
        }

        public IActionResult Index()
        {
            return View(_dbContext.Comments.ToList());
        }

        
    }
}

GuestBookCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using GuestBookCore.Models;

namespace GuestBookCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GuestBookCore/Views/Comment/Create.cshtml
@model GuestBookCore.Models.ViewModels.CommentViewModel

@*@{
    ViewData["Title"] = "Create";
}*@

    <form asp-controller="Comment" asp-action="Create">
        <div asp-validation-summary="ModelOnly"></div>
        <div>
            <label asp-for="Username"></label>
            <input asp-for="Username" />
            <div><span asp-validation-for="Username"></span></div>
        </div>
        <div>
            <label asp-for="Text"></label>
            <input asp-for="Text" />
            <div><span asp-validation-for="Text"></span></div>
        </div>
        <div>
            <input type="submit" value="Добавить" />
        </div>
    </form>

GuestBookCore/Views/Comment/Index.cshtml
@model IEnumerable<GuestBookCore.Models.Entities.Comment>

@{
    ViewData["Title"] = "Index";
}

<h1>Гостевая книга</h1>
<a asp-controller="Comment" asp-action="Create">Добавить комментарий</a>
<ul>
    @foreach (var item in Model)
    {
        @await Html.PartialAsync("_CommentPartial", item)
    }
</ul>

GuestBookCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GuestBookCore/Views/Shared/_CommentPartial.cshtml
@model GuestBookCore.Models.Entities.Comment

<div>
    <div><strong>@Model.Username</strong>   @Model.Date</div>
    <div>@Model.Text</div>
</div>

GuestBookCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuestBookCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GuestBookCore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GuestBookCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>